name: Test Suite

on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened, converted_to_draft]

jobs:
    php_tests:
        if: "!contains(github.event.head_commit.message, 'changelog')"

        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                php: [8.1, 8.2, 8.3, 8.4]
                laravel: [10.*, 11.*, 12.*]
                statamic: [4.*, 5.*]
                os: [ubuntu-latest]
                exclude:
                    - php: 8.2
                      laravel: 10.*
                    - php: 8.3
                      laravel: 10.*
                    - php: 8.4
                      laravel: 10.*
                    - statamic: 4.*
                      laravel: 11.*
                    - statamic: 4.*
                      laravel: 12.*

        name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - Statamic ${{ matrix.statamic }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick

            - name: Install dependencies
              run: |
                  composer require "illuminate/contracts:${{ matrix.laravel }}" --no-interaction --no-update
                  composer require "statamic/cms:${{ matrix.statamic }}" --no-interaction --no-update
                  composer update --prefer-dist --no-interaction --no-suggest

            - name: Run PHPUnit
              run: vendor/bin/phpunit
